# Generated by Django 6.0.1 on 2026-01-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='headline',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
